Module2 task2
htmlacademy-php1/581221-doingsdone-14 pull request #4
Opened 2022-04-15 10:42 UTC by artemevskih

2022-04-15 13:31 UTC, artemevskih commented
Хотел спросить, как правильно именовать переменные и функции, камелкэйсом или через подчеркивание?

2022-04-17 08:47 UTC, ademaro commented on index.php
> +
phpDoc давай добавим

2022-04-17 08:48 UTC, ademaro commented on index.php
> +    function get_number(array $list, string $name) {
get_number — ну как-то совсем непонятно что за номер функция должна забирать)) Давай подумаем как назвать лучше)

2022-04-17 08:49 UTC, ademaro commented on index.php
> +    function get_number(array $list, string $name) {
про параметры — так же, list — это же массив задач, так и назови как tasks, например. Второй не name, а category_name хотя бы

2022-04-17 08:50 UTC, ademaro commented on index.php
> +        foreach ($list as $item) {
$item так же замени

2022-04-17 08:51 UTC, ademaro requested changes
В целом всё отлично! Могу закрыть, но давай попробуем отработать случай когда я не принимаю ПР) Сделай поправки в этом же ПРе и отправь повторно на проверку в интерфейсе академии

2022-04-19 10:01 UTC, artemevskih commented on index.php
> +
Только комментарии или установить надо?

2022-04-20 08:14 UTC, ademaro approved these changes

2022-04-20 08:14 UTC, merged